CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE,
    phone VARCHAR(20) UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO web_app_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO web_app_user;

SELECT * FROM users;